# Generated by Django on data migration
from django.db import migrations
from django.contrib.auth.hashers import make_password

def seed_legacy_accounts(apps, schema_editor):
    Company = apps.get_model('myapp', 'Company')
    Employee = apps.get_model('myapp', 'Employee')

    co_email = 'admin@teamnext.test'.strip().lower()
    emp_email = 'admin@teamnext.test'.strip().lower()

    company = Company.objects.filter(email__iexact=co_email).first()
    if not company:
        company = Company.objects.create(
            name='TeamNext Enterprise',
            email=co_email,
            password=make_password('TeamNextAdmin2026!'),
            address='Corporate HQ',
            phone='18005550199',
            website='https://teamnexterp.com',
            employees_count='50-200',
            industry='Technology'
        )

    employee = Employee.objects.filter(email__iexact=emp_email).first()
    if not employee:
        Employee.objects.create(
            company=company,
            name='Enterprise Administrator',
            email=emp_email,
            password=make_password('TeamNextAdmin2026!'),
            role='Administrator',
            department_old='Executive',
            phone='18005550199'
        )

def unseed_legacy_accounts(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_legacy_accounts, unseed_legacy_accounts),
    ]
